// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_Associate_Populating.Models;

public partial class Owner
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public virtual ICollection<Dog> Dogs { get; set; } = new List<Dog>();

    public override string ToString()
    {
         return $"Owner Id: {Id}, Name: {Name}, Image: {Image}";
    }
}