// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_Associate_Populating.Models;

public partial class Toy
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    public bool HasSqueeker { get; set; }

    public virtual ICollection<DogToy> DogToys { get; set; } = new List<DogToy>();
}