// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_Selecting_Data.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string CourseName { get; set; }

    public int TermCode { get; set; }

    public string CourseNumber { get; set; }

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();


    public override string ToString()
    {
        return $"{CourseName} ({CourseNumber.Trim()})";
    }

}