// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EF_Reading_Data.Models;

public partial class DB_128040_practiceContext : DbContext
{
    public DB_128040_practiceContext()
    {
    }

    public DB_128040_practiceContext(DbContextOptions<DB_128040_practiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FootballSchedule> FootballSchedules { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=tcp:s13.winhost.com;Initial Catalog=DB_128040_practice;Persist Security Info=True;User ID=student;Password=AdamTheGreat2020;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FootballSchedule>(entity =>
        {
            entity.ToTable("FootballSchedule");

            entity.Property(e => e.Opponent)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}