// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_Reading_Data.Models;

public partial class FootballSchedule
{
    public int Id { get; set; }

    public int Season { get; set; }

    public string Opponent { get; set; }

    public DateOnly Date { get; set; }

    public bool IsHomeGame { get; set; }

    public override string ToString()
    {
        return $"{Date.ToShortDateString()} - {(IsHomeGame ? "Home" : "Away")} vs. {Opponent.Trim()} (Season {Season})"; 
    }
}